default:
	 make clean
	 g++ correct.c -o correct_correct
	 ./correct_correct > output_correct
	 llvm-gcc -emit-llvm correct.c -c -o correct.bc
	 opt -loop-simplify correct.bc -o correct.ls.bc
	 llc correct.ls.bc -o correct.ls.s
	 g++ -o correct.ls correct.ls.s
	 ./correct.ls > output_correct_ls
	 opt -mem2reg correct.ls.bc -o correct.ls.mem2reg.bc
	 llc correct.ls.mem2reg.bc -o correct.ls.mem2reg.s
	 g++ -o correct.ls.mem2reg correct.ls.mem2reg.s
	 opt -insert-edge-profiling correct.ls.bc -o correct.profile.bc
	 llc correct.profile.bc -o correct.profile.s
	 g++ -o correct.profile correct.profile.s /y/students/mviscomi/llvm-install/Release/lib/profile_rt.so
	 -./correct.profile > output_profile
	 opt -load ../../Debug+Asserts/lib/projpass.so -lamp-insts -insert-lamp-profiling -insert-lamp-loop-profiling -insert-lamp-init < correct.ls.bc > correct.lamp.bc
	 llc correct.lamp.bc -o correct.lamp.s
	 g++ -o correct.lamp correct.lamp.s /y/students/mviscomi/llvm-install/Release/lib/profile_rt.so ../../tools/lamp-profiler/lamp_hooks.o ../../tools/lamp-profiler/loadstride.cxx
	 -./correct.lamp > output
	 opt -load ../../Debug+Asserts/lib/projpass.so -profile-loader -profile-info-file=llvmprof.out -lamp-inst-cnt -lamp-map-loop -lamp-load-profile -projpass correct.ls.bc > correct.slicm.bc
	llc correct.slicm.bc -o correct.slicm.s
	g++ -o correct.slicm correct.slicm.s
	opt -dot-cfg correct.slicm.bc >& /dev/null
	mv cfg.main.dot cfg.slicm.dot
	opt -dot-cfg correct.bc >& /dev/null
	mv cfg.main.dot cfg.correct.dot
	rm -f cfg.main.dot
	opt -mem2reg correct.slicm.bc -o correct.slicm.mem2reg.bc
	llc correct.slicm.mem2reg.bc -o correct.slicm.mem2reg.s
	g++ -o correct.slicm.mem2reg correct.slicm.mem2reg.s
	opt -dot-cfg correct.slicm.mem2reg.bc >& /dev/null
	mv cfg.main.dot cfg.slicm.mem2reg.dot
	rm -f cfg.main.dot

	-./correct.slicm.mem2reg > output_slicm
	-./correct.ls.mem2reg > output_correct_ls_mem2reg
	tail output_correct_ls_mem2reg
	tail output_slicm
	
clean:
	rm -f llvmprof.out
	rm -f correct_correct output_correct
	rm -f result.lamp*
	rm -f correct.bc correct.opt*
	rm -f output output_slicm correct.lamp* correct.ls* correct.profile* output_*
	rm -f correct.slicm*
	rm -f cfg.*

#	 opt -loop-simplify < simple.bc > simple.ls.bc
#	 opt -load /y/students/mviscomi/hw1/Debug+Asserts/lib/sample.so -lamp-insts -insert-lamp-profiling -insert-lamp-loop-profiling -insert-lamp-init < simple.ls.bc > simple.lamp.bc
#	 llc < simple.lamp.bc > simple.lamp.s
#	 g++ -o simple.lamp.exe simple.lamp.s /y/students/mviscomi/hw1/tools/lamp-profiler/lamp_hooks.o
#	 -./simple.lamp.exe > output.lamp
