##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..
LOADABLE_MODULE=1
#
# List all of the subdirectories that we will compile.
#
DIRS=hw1pass

include $(LEVEL)/Makefile.common
